### PR TITLE
PyScript Post

### PR DESCRIPTION
**Pull request by MarkRoddy**

### CODE REVIEW

**Comment by roycoding** [comment]
Looks pretty good to me.

You clearly have more web programming experience than I do, so there were a couple things that didn't mean a lot to me, being much more in the Python (non-web) world.

It might be useful to try to put this in the context of other tools that Python-writing people are currently using, such as Streamlit.

**Comment by MarkRoddy** [comment]
Thanks for the feedback @roycoding! If you can give any of the examples of things that didn't mean much that would be useful for me to clarify.

**Comment by roycoding** [comment]
Mostly stuff related to the DOM, I suppose.

I think it's probably worthwhile to have, but maybe possibly more of a "from the (JS) web developer point of view, some of the issues are A, B, and C" and "from the Python developer point of view, some of the issues are X, Y, and Z". Since you straddle a bit of both worlds.

**Comment by roycoding** [comment]
Mostly stuff related to the DOM, I suppose.

I think it's probably worthwhile to have, but maybe possibly more of a "from the (JS) web developer point of view, some of the issues are A, B, and C" and "from the Python developer point of view, some of the issues are X, Y, and Z". Since you straddle a bit of both worlds.

I don't personally care about a "JS killer", but I do care about whether this is a tool that I should be using to present data / results or make relatively simply app for web browsers (from the data/ml Python person point of view)

**Pull request closed without merging**
